# Argo CD Application for the Gitea Database
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-application
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
  source:
    path: charts/immich
    repoURL: https://github.com/seaser0/immich-charts.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - custom_values.yaml