apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: immich-storage
provisioner: cluster.local/nfs-subdir-external-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich-storage # A custom StorageClass for immich
  nfs:
    path: /mnt/pool02/conatiner_pvc/dev/immich
    server: truenas02.nevit.ch
  mountOptions:
    - nfsvers=4.2
    - hard
    - timeo=600
    - retrans=2
    - rsize=1048576
    - wsize=1048576
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: immich-storage
