kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: immich-storage
provisioner: cluster.local/nfs-subdir-external-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich-storage
  nfs:
    path: /mnt/pool01/containers/immich
    server: 192.168.1.100