---
apiVersion: v2
description: A chart to power Immich (immich.app) running on kubernetes
name: immich
version: 0.8.4
appVersion: v1.121.0
home: https://immich.app/
icon: https://raw.githubusercontent.com/immich-app/immich/main/design/immich-logo.svg
sources:
  - https://github.com/seaser0/immich-charts.git
maintainers:
  - name: Seaser0
    email: seaser0@users.noreply.github.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.4.0
  - name: postgresql
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 15.9.0
  - name: redis
    condition: redis.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 19.5.3
annotations:
  artifacthub.io/category: storage
  artifacthub.io/changes: |-
    - kind: changed
      description: Bumped pgvecto-rs to pg14-v0.2.0
      links:
        - name: Release Notes Breaking Changes
          url: https://github.com/immich-app/immich/releases/tag/v1.95.1
